# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be7c0a1a66060a7949d3f1c830ccb8f0550e5a20c09951cb61a3cc74dd8dd8627e75237139f94abbd1cf64084043b1d1e0ddec4a4d516dc5f970c1110714a56b

test:
  secret_key_base: 8d01c781551d1602ab12a5ad4b2e1af0f358f90b3910364407880596c4c45cad6d77d28e02477d35d34685f95285688e433a7176c6145c1a4ec82b5453ca8cce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
